/* gclip_select.c generated by valac 0.18.1, the Vala compiler
 * generated from gclip_select.vala, do not modify */

/*
Copyright 2011, 2013 Li-Cheng (Andy) Tai
                      atai@atai.org
                      
gclip_select is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option)
any later version.

gclip_select is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along with
gclip_select. If not, see http://www.gnu.org/licenses/.


*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <gdk/gdk.h>
#include <time.h>

typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block2Data Block2Data;
typedef struct _Block3Data Block3Data;
#define _g_source_unref0(var) ((var == NULL) ? NULL : (var = (g_source_unref (var), NULL)))

struct _Block1Data {
	int _ref_count_;
	GtkListStore* list_model;
	GtkTreeSelection* selection;
};

struct _Block2Data {
	int _ref_count_;
	GtkScrolledWindow* list_view;
	GtkTreeView* list_box;
	gchar* content;
};

struct _Block3Data {
	int _ref_count_;
	Block2Data * _data2_;
	gint WAIT_TIME;
};


extern gboolean self_clip_set;
gboolean self_clip_set = FALSE;
extern gboolean new_insert;
gboolean new_insert = FALSE;
extern GtkClipboard* clip;
GtkClipboard* clip = NULL;
extern guint32 selection_time;
guint32 selection_time = (guint32) 0;
extern GeeHashMap* content_table;
GeeHashMap* content_table = NULL;
extern GtkButton* delete_button;
GtkButton* delete_button = NULL;
extern GtkButton* delete_all_button;
GtkButton* delete_all_button = NULL;

void setup_list_box (GtkTreeView* list_box);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda2_ (Block1Data* _data1_);
static void ___lambda2__gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
void add_entry_to_list_box (GtkTreeView* list_box, const gchar* content);
void delete_current_selection (GtkTreeView* list_box);
static gboolean _gtk_tree_iter_equal (const GtkTreeIter* s1, const GtkTreeIter* s2);
void delete_all_selection (GtkTreeView* list_box);
gint _vala_main (gchar** args, int args_length1);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static GtkTreeIter* _gtk_tree_iter_dup (GtkTreeIter* self);
static gboolean __lambda3_ (Block2Data* _data2_);
static gboolean ___lambda3__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean __lambda4_ (Block2Data* _data2_);
static gboolean ___lambda4__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void __lambda5_ (Block2Data* _data2_, GdkEvent* e);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static gboolean __lambda6_ (Block3Data* _data3_);
static gboolean ___lambda6__gsource_func (gpointer self);
static void ___lambda5__gtk_clipboard_owner_change (GtkClipboard* _sender, GdkEvent* p0, gpointer self);
static void __lambda7_ (Block2Data* _data2_, GtkAllocation* rect);
static void ___lambda7__gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self);


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return _data1_;
#line 110 "gclip_select.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_object_unref0 (_data1_->selection);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_object_unref0 (_data1_->list_model);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		g_slice_free (Block1Data, _data1_);
#line 125 "gclip_select.c"
	}
}


static gpointer _g_object_ref0 (gpointer self) {
#line 50 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return self ? g_object_ref (self) : NULL;
#line 133 "gclip_select.c"
}


static void __lambda2_ (Block1Data* _data1_) {
	GtkTreeIter iter = {0};
	GtkTreeModel* model = NULL;
	gchar* content = NULL;
	GtkTreeModel* _tmp0_ = NULL;
	GtkTreeIter _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	GtkTreeModel* _tmp3_;
#line 57 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp2_ = gtk_tree_selection_get_selected (_data1_->selection, &_tmp0_, &_tmp1_);
#line 57 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (model);
#line 57 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp3_ = _g_object_ref0 (_tmp0_);
#line 57 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	model = _tmp3_;
#line 57 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	iter = _tmp1_;
#line 57 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (_tmp2_) {
#line 157 "gclip_select.c"
		GtkTreeIter _tmp4_;
		gboolean _tmp5_;
		GtkButton* _tmp8_;
#line 59 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp4_ = iter;
#line 59 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_tree_model_get ((GtkTreeModel*) _data1_->list_model, &_tmp4_, 0, &content, -1, -1);
#line 61 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp5_ = new_insert;
#line 61 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		if (!_tmp5_) {
#line 169 "gclip_select.c"
			GtkClipboard* _tmp6_;
			const gchar* _tmp7_;
#line 63 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp6_ = clip;
#line 63 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp7_ = content;
#line 63 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			gtk_clipboard_set_text (_tmp6_, _tmp7_, -1);
#line 64 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			self_clip_set = TRUE;
#line 180 "gclip_select.c"
		}
#line 67 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp8_ = delete_button;
#line 67 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp8_, TRUE);
#line 186 "gclip_select.c"
	} else {
		GtkButton* _tmp9_;
#line 71 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp9_ = delete_button;
#line 71 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp9_, FALSE);
#line 193 "gclip_select.c"
	}
#line 52 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_free0 (content);
#line 52 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (model);
#line 199 "gclip_select.c"
}


static void ___lambda2__gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
#line 52 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	__lambda2_ (self);
#line 206 "gclip_select.c"
}


void setup_list_box (GtkTreeView* list_box) {
	Block1Data* _data1_;
	GtkListStore* _tmp0_;
	GtkTreeView* _tmp1_;
	GtkTreeView* _tmp2_;
	GtkCellRendererText* _tmp3_;
	GtkCellRendererText* text_renderer;
	GtkTreeView* _tmp4_;
	GtkTreeView* _tmp5_;
	GtkTreeView* _tmp6_;
	GtkTreeSelection* _tmp7_ = NULL;
	GtkTreeSelection* _tmp8_;
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_return_if_fail (list_box != NULL);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data1_->_ref_count_ = 1;
#line 41 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = gtk_list_store_new (1, G_TYPE_STRING);
#line 41 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data1_->list_model = _tmp0_;
#line 42 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp1_ = list_box;
#line 42 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_tree_view_set_rules_hint (_tmp1_, TRUE);
#line 43 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp2_ = list_box;
#line 43 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_tree_view_set_model (_tmp2_, (GtkTreeModel*) _data1_->list_model);
#line 44 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp3_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 44 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp3_);
#line 44 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	text_renderer = _tmp3_;
#line 45 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_set (text_renderer, "ellipsize-set", TRUE, NULL);
#line 46 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_set (text_renderer, "ellipsize", PANGO_ELLIPSIZE_END, NULL);
#line 48 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp4_ = list_box;
#line 48 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_tree_view_insert_column_with_attributes (_tmp4_, -1, "Clip content Selector", (GtkCellRenderer*) text_renderer, "text", 0, NULL);
#line 49 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp5_ = list_box;
#line 49 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_tree_view_set_headers_visible (_tmp5_, FALSE);
#line 50 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp6_ = list_box;
#line 50 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp7_ = gtk_tree_view_get_selection (_tmp6_);
#line 50 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp8_ = _g_object_ref0 (_tmp7_);
#line 50 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data1_->selection = _tmp8_;
#line 52 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_signal_connect_data (_data1_->selection, "changed", (GCallback) ___lambda2__gtk_tree_selection_changed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (text_renderer);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	block1_data_unref (_data1_);
#line 39 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data1_ = NULL;
#line 274 "gclip_select.c"
}


void add_entry_to_list_box (GtkTreeView* list_box, const gchar* content) {
	GtkTreeIter iter = {0};
	const gchar* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_ = NULL;
	gchar* cksum;
	GeeHashMap* _tmp5_;
	const gchar* _tmp6_;
	gboolean _tmp7_ = FALSE;
	GtkTreeView* _tmp23_;
	GtkTreeSelection* _tmp24_ = NULL;
	GtkTreeSelection* _tmp25_;
	GtkTreeSelection* selection;
	GtkTreeSelection* _tmp26_;
	GtkTreeIter _tmp27_;
	GtkButton* _tmp28_;
	GtkButton* _tmp29_;
#line 79 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_return_if_fail (list_box != NULL);
#line 79 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_return_if_fail (content != NULL);
#line 82 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = content;
#line 82 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp1_ = strlen (_tmp0_);
#line 82 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp2_ = _tmp1_;
#line 82 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (_tmp2_ == 0) {
#line 83 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return;
#line 311 "gclip_select.c"
	}
#line 84 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp3_ = content;
#line 84 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp4_ = g_compute_checksum_for_string (G_CHECKSUM_SHA256, _tmp3_, (gsize) (-1));
#line 84 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	cksum = _tmp4_;
#line 85 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp5_ = content_table;
#line 85 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp6_ = cksum;
#line 85 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp7_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp5_, _tmp6_);
#line 85 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (_tmp7_) {
#line 327 "gclip_select.c"
		GeeHashMap* _tmp8_;
		const gchar* _tmp9_;
		gpointer _tmp10_ = NULL;
		GtkTreeIter* _tmp11_;
#line 87 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp8_ = content_table;
#line 87 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp9_ = cksum;
#line 87 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp10_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp8_, _tmp9_);
#line 87 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp11_ = (GtkTreeIter*) _tmp10_;
#line 87 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		iter = *_tmp11_;
#line 87 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_free0 (_tmp11_);
#line 344 "gclip_select.c"
	} else {
		GtkTreeView* _tmp12_;
		GtkTreeModel* _tmp13_ = NULL;
		GtkListStore* _tmp14_;
		GtkListStore* list_model;
		GtkListStore* _tmp15_;
		GtkTreeIter _tmp16_ = {0};
		GtkListStore* _tmp17_;
		GtkTreeIter _tmp18_;
		const gchar* _tmp19_;
		GeeHashMap* _tmp20_;
		const gchar* _tmp21_;
		GtkTreeIter _tmp22_;
#line 92 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp12_ = list_box;
#line 92 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp13_ = gtk_tree_view_get_model (_tmp12_);
#line 92 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp14_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, GTK_TYPE_LIST_STORE, GtkListStore));
#line 92 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		list_model = _tmp14_;
#line 93 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp15_ = list_model;
#line 93 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_list_store_append (_tmp15_, &_tmp16_);
#line 93 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		iter = _tmp16_;
#line 95 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp17_ = list_model;
#line 95 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp18_ = iter;
#line 95 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp19_ = content;
#line 95 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_list_store_set (_tmp17_, &_tmp18_, 0, _tmp19_, -1);
#line 96 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp20_ = content_table;
#line 96 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp21_ = cksum;
#line 96 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp22_ = iter;
#line 96 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gee_abstract_map_set ((GeeAbstractMap*) _tmp20_, _tmp21_, &_tmp22_);
#line 97 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		new_insert = TRUE;
#line 85 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_object_unref0 (list_model);
#line 392 "gclip_select.c"
	}
#line 99 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp23_ = list_box;
#line 99 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp24_ = gtk_tree_view_get_selection (_tmp23_);
#line 99 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp25_ = _g_object_ref0 (_tmp24_);
#line 99 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	selection = _tmp25_;
#line 100 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp26_ = selection;
#line 100 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp27_ = iter;
#line 100 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_tree_selection_select_iter (_tmp26_, &_tmp27_);
#line 102 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp28_ = delete_button;
#line 102 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp28_, TRUE);
#line 103 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp29_ = delete_all_button;
#line 103 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp29_, TRUE);
#line 79 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (selection);
#line 79 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_free0 (cksum);
#line 420 "gclip_select.c"
}


static gboolean _gtk_tree_iter_equal (const GtkTreeIter* s1, const GtkTreeIter* s2) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (s1 == s2) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return TRUE;
#line 429 "gclip_select.c"
	}
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (s1 == NULL) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return FALSE;
#line 435 "gclip_select.c"
	}
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (s2 == NULL) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return FALSE;
#line 441 "gclip_select.c"
	}
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (s1->stamp != s2->stamp) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return FALSE;
#line 447 "gclip_select.c"
	}
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (s1->user_data != s2->user_data) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return FALSE;
#line 453 "gclip_select.c"
	}
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (s1->user_data2 != s2->user_data2) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return FALSE;
#line 459 "gclip_select.c"
	}
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (s1->user_data3 != s2->user_data3) {
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		return FALSE;
#line 465 "gclip_select.c"
	}
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return TRUE;
#line 469 "gclip_select.c"
}


void delete_current_selection (GtkTreeView* list_box) {
	GtkTreeView* _tmp0_;
	GtkTreeSelection* _tmp1_ = NULL;
	GtkTreeSelection* _tmp2_;
	GtkTreeSelection* selection;
	GtkTreeIter iter = {0};
	GtkTreeModel* model = NULL;
	GtkTreeSelection* _tmp3_;
	GtkTreeModel* _tmp4_ = NULL;
	GtkTreeIter _tmp5_ = {0};
	gboolean _tmp6_ = FALSE;
	GtkTreeModel* _tmp7_;
	GtkTreeSelection* _tmp36_;
	GtkTreeModel* _tmp37_ = NULL;
	GtkTreeIter _tmp38_ = {0};
	gboolean _tmp39_ = FALSE;
	GtkTreeModel* _tmp40_;
#line 108 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_return_if_fail (list_box != NULL);
#line 110 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = list_box;
#line 110 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp1_ = gtk_tree_view_get_selection (_tmp0_);
#line 110 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 110 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	selection = _tmp2_;
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp3_ = selection;
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp6_ = gtk_tree_selection_get_selected (_tmp3_, &_tmp4_, &_tmp5_);
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (model);
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp7_ = _g_object_ref0 (_tmp4_);
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	model = _tmp7_;
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	iter = _tmp5_;
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (_tmp6_) {
#line 514 "gclip_select.c"
		GtkTreeModel* _tmp8_;
		GtkListStore* _tmp9_;
		GtkListStore* list_model;
		GtkTreeSelection* _tmp28_;
		GtkTreeIter _tmp29_;
		GtkListStore* _tmp30_;
		GtkTreeIter _tmp31_;
		GtkListStore* _tmp32_;
		GtkTreeIter _tmp33_ = {0};
		gboolean _tmp34_ = FALSE;
#line 116 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp8_ = model;
#line 116 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp9_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, GTK_TYPE_LIST_STORE, GtkListStore));
#line 116 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		list_model = _tmp9_;
#line 531 "gclip_select.c"
		{
			GeeHashMap* _tmp10_;
			GeeSet* _tmp11_;
			GeeSet* _tmp12_;
			GeeSet* _tmp13_;
			GeeIterator* _tmp14_ = NULL;
			GeeIterator* _tmp15_;
			GeeIterator* _entry_it;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp10_ = content_table;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp11_ = gee_abstract_map_get_entries ((GeeMap*) _tmp10_);
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp12_ = _tmp11_;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp13_ = _tmp12_;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp14_ = gee_iterable_iterator ((GeeIterable*) _tmp13_);
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp15_ = _tmp14_;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_g_object_unref0 (_tmp13_);
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_entry_it = _tmp15_;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			while (TRUE) {
#line 558 "gclip_select.c"
				GeeIterator* _tmp16_;
				gboolean _tmp17_ = FALSE;
				GeeIterator* _tmp18_;
				gpointer _tmp19_ = NULL;
				GeeMapEntry* entry;
				GeeMapEntry* _tmp20_;
				gconstpointer _tmp21_;
				GtkTreeIter* _tmp22_;
				GtkTreeIter _tmp23_;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp16_ = _entry_it;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp17_ = gee_iterator_next (_tmp16_);
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				if (!_tmp17_) {
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					break;
#line 576 "gclip_select.c"
				}
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp18_ = _entry_it;
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp19_ = gee_iterator_get (_tmp18_);
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				entry = (GeeMapEntry*) _tmp19_;
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp20_ = entry;
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp21_ = gee_map_entry_get_value (_tmp20_);
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp22_ = _tmp21_;
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_tmp23_ = iter;
#line 119 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				if (_gtk_tree_iter_equal ((GtkTreeIter*) _tmp22_, &_tmp23_) == TRUE) {
#line 594 "gclip_select.c"
					GeeHashMap* _tmp24_;
					GeeMapEntry* _tmp25_;
					gconstpointer _tmp26_;
					const gchar* _tmp27_;
#line 121 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					_tmp24_ = content_table;
#line 121 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					_tmp25_ = entry;
#line 121 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					_tmp26_ = gee_map_entry_get_key (_tmp25_);
#line 121 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					_tmp27_ = _tmp26_;
#line 121 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					gee_abstract_map_unset ((GeeAbstractMap*) _tmp24_, (const gchar*) _tmp27_, NULL);
#line 122 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					_g_object_unref0 (entry);
#line 122 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
					break;
#line 613 "gclip_select.c"
				}
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
				_g_object_unref0 (entry);
#line 617 "gclip_select.c"
			}
#line 117 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_g_object_unref0 (_entry_it);
#line 621 "gclip_select.c"
		}
#line 126 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp28_ = selection;
#line 126 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp29_ = iter;
#line 126 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_tree_selection_unselect_iter (_tmp28_, &_tmp29_);
#line 127 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp30_ = list_model;
#line 127 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp31_ = iter;
#line 127 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_list_store_remove (_tmp30_, &_tmp31_);
#line 128 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp32_ = list_model;
#line 128 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp34_ = gtk_tree_model_get_iter_first ((GtkTreeModel*) _tmp32_, &_tmp33_);
#line 128 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		iter = _tmp33_;
#line 128 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		if (_tmp34_ == FALSE) {
#line 643 "gclip_select.c"
			GtkButton* _tmp35_;
#line 129 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp35_ = delete_all_button;
#line 129 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			gtk_widget_set_sensitive ((GtkWidget*) _tmp35_, FALSE);
#line 649 "gclip_select.c"
		}
#line 113 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_object_unref0 (list_model);
#line 653 "gclip_select.c"
	}
#line 131 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp36_ = selection;
#line 131 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp39_ = gtk_tree_selection_get_selected (_tmp36_, &_tmp37_, &_tmp38_);
#line 131 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (model);
#line 131 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp40_ = _g_object_ref0 (_tmp37_);
#line 131 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	model = _tmp40_;
#line 131 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	iter = _tmp38_;
#line 131 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (!_tmp39_) {
#line 669 "gclip_select.c"
		GtkButton* _tmp41_;
#line 133 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp41_ = delete_button;
#line 133 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp41_, FALSE);
#line 675 "gclip_select.c"
	}
#line 108 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (model);
#line 108 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (selection);
#line 681 "gclip_select.c"
}


void delete_all_selection (GtkTreeView* list_box) {
	GtkTreeView* _tmp0_;
	GtkTreeModel* _tmp1_ = NULL;
	GtkListStore* _tmp2_;
	GtkListStore* list_model;
	GtkTreeView* _tmp3_;
	GtkTreeSelection* _tmp4_ = NULL;
	GtkTreeSelection* _tmp5_;
	GtkTreeSelection* selection;
	GeeHashMap* _tmp6_;
	GtkButton* _tmp7_;
	GtkButton* _tmp8_;
#line 138 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_return_if_fail (list_box != NULL);
#line 140 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = list_box;
#line 140 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp1_ = gtk_tree_view_get_model (_tmp0_);
#line 140 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GTK_TYPE_LIST_STORE, GtkListStore));
#line 140 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	list_model = _tmp2_;
#line 141 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp3_ = list_box;
#line 141 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp4_ = gtk_tree_view_get_selection (_tmp3_);
#line 141 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 141 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	selection = _tmp5_;
#line 142 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_tree_selection_unselect_all (selection);
#line 143 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_list_store_clear (list_model);
#line 144 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp6_ = content_table;
#line 144 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gee_abstract_map_clear ((GeeAbstractMap*) _tmp6_);
#line 145 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp7_ = delete_button;
#line 145 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp7_, FALSE);
#line 146 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp8_ = delete_all_button;
#line 146 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp8_, FALSE);
#line 138 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (selection);
#line 138 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (list_model);
#line 735 "gclip_select.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return _data2_;
#line 744 "gclip_select.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_free0 (_data2_->content);
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_object_unref0 (_data2_->list_box);
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_object_unref0 (_data2_->list_view);
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		g_slice_free (Block2Data, _data2_);
#line 761 "gclip_select.c"
	}
}


static GtkTreeIter* _gtk_tree_iter_dup (GtkTreeIter* self) {
	GtkTreeIter* dup;
#line 154 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	dup = g_new0 (GtkTreeIter, 1);
#line 154 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	memcpy (dup, self, sizeof (GtkTreeIter));
#line 154 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return dup;
#line 774 "gclip_select.c"
}


static gboolean __lambda3_ (Block2Data* _data2_) {
	gboolean result = FALSE;
	GtkTreeView* _tmp0_;
#line 178 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = _data2_->list_box;
#line 178 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	delete_current_selection (_tmp0_);
#line 179 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	result = FALSE;
#line 179 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return result;
#line 789 "gclip_select.c"
}


static gboolean ___lambda3__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda3_ (self);
#line 176 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return result;
#line 798 "gclip_select.c"
}


static gboolean __lambda4_ (Block2Data* _data2_) {
	gboolean result = FALSE;
	GtkTreeView* _tmp0_;
#line 185 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = _data2_->list_box;
#line 185 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	delete_all_selection (_tmp0_);
#line 186 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	result = FALSE;
#line 186 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return result;
#line 813 "gclip_select.c"
}


static gboolean ___lambda4__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda4_ (self);
#line 183 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return result;
#line 822 "gclip_select.c"
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 205 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_main_quit ();
#line 829 "gclip_select.c"
}


static Block3Data* block3_data_ref (Block3Data* _data3_) {
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return _data3_;
#line 838 "gclip_select.c"
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		block2_data_unref (_data3_->_data2_);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_data3_->_data2_ = NULL;
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		g_slice_free (Block3Data, _data3_);
#line 853 "gclip_select.c"
	}
}


static gboolean __lambda6_ (Block3Data* _data3_) {
	Block2Data* _data2_;
	gboolean result = FALSE;
	time_t _tmp0_;
	guint32 _tmp1_;
#line 212 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data2_ = _data3_->_data2_;
#line 214 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = time (NULL);
#line 214 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp1_ = selection_time;
#line 214 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if ((_tmp0_ - _tmp1_) >= ((time_t) _data3_->WAIT_TIME)) {
#line 871 "gclip_select.c"
		gboolean _tmp2_;
#line 216 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp2_ = self_clip_set;
#line 216 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		if (!_tmp2_) {
#line 877 "gclip_select.c"
			GtkClipboard* _tmp3_;
			gchar* _tmp4_ = NULL;
			GtkTreeView* _tmp5_;
			const gchar* _tmp6_;
#line 218 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp3_ = clip;
#line 218 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp4_ = gtk_clipboard_wait_for_text (_tmp3_);
#line 218 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_g_free0 (_data2_->content);
#line 218 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_data2_->content = _tmp4_;
#line 219 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp5_ = _data2_->list_box;
#line 219 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			_tmp6_ = _data2_->content;
#line 219 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			add_entry_to_list_box (_tmp5_, _tmp6_);
#line 896 "gclip_select.c"
		} else {
#line 222 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
			self_clip_set = FALSE;
#line 900 "gclip_select.c"
		}
	}
#line 224 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	result = FALSE;
#line 224 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return result;
#line 907 "gclip_select.c"
}


static gboolean ___lambda6__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda6_ (self);
#line 212 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return result;
#line 916 "gclip_select.c"
}


static void __lambda5_ (Block2Data* _data2_, GdkEvent* e) {
	Block3Data* _data3_;
	GdkEvent* _tmp0_;
	guint32 _tmp1_ = 0U;
	GSource* _tmp2_;
	GSource* time_out;
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_return_if_fail (e != NULL);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data3_ = g_slice_new0 (Block3Data);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data3_->_ref_count_ = 1;
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data3_->_data2_ = block2_data_ref (_data2_);
#line 209 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data3_->WAIT_TIME = 900;
#line 210 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = e;
#line 210 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp1_ = gdk_event_get_time (_tmp0_);
#line 210 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	selection_time = _tmp1_;
#line 211 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp2_ = g_timeout_source_new ((guint) _data3_->WAIT_TIME);
#line 211 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	time_out = _tmp2_;
#line 212 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_source_set_callback (time_out, ___lambda6__gsource_func, block3_data_ref (_data3_), block3_data_unref);
#line 227 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_source_attach (time_out, NULL);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_source_unref0 (time_out);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	block3_data_unref (_data3_);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data3_ = NULL;
#line 956 "gclip_select.c"
}


static void ___lambda5__gtk_clipboard_owner_change (GtkClipboard* _sender, GdkEvent* p0, gpointer self) {
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	__lambda5_ (self, p0);
#line 963 "gclip_select.c"
}


static void __lambda7_ (Block2Data* _data2_, GtkAllocation* rect) {
	gboolean _tmp0_;
#line 232 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_return_if_fail (rect != NULL);
#line 235 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = new_insert;
#line 235 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (_tmp0_) {
#line 975 "gclip_select.c"
		GtkScrolledWindow* _tmp1_;
		GtkAdjustment* _tmp2_;
		GtkAdjustment* _tmp3_;
		GtkAdjustment* _tmp4_;
		GtkAdjustment* vadj;
		GtkAdjustment* _tmp5_;
		GtkAdjustment* _tmp6_;
		gdouble _tmp7_;
		gdouble _tmp8_;
		GtkAdjustment* _tmp9_;
		gdouble _tmp10_;
		gdouble _tmp11_;
#line 237 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp1_ = _data2_->list_view;
#line 237 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp2_ = gtk_scrolled_window_get_vadjustment (_tmp1_);
#line 237 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp3_ = _tmp2_;
#line 237 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp4_ = _g_object_ref0 (_tmp3_);
#line 237 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		vadj = _tmp4_;
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp5_ = vadj;
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp6_ = vadj;
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp7_ = gtk_adjustment_get_upper (_tmp6_);
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp8_ = _tmp7_;
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp9_ = vadj;
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp10_ = gtk_adjustment_get_page_size (_tmp9_);
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp11_ = _tmp10_;
#line 239 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		gtk_adjustment_set_value (_tmp5_, _tmp8_ - _tmp11_);
#line 235 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_g_object_unref0 (vadj);
#line 1016 "gclip_select.c"
	}
#line 241 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	new_insert = FALSE;
#line 1020 "gclip_select.c"
}


static void ___lambda7__gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self) {
#line 232 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	__lambda7_ (self, allocation);
#line 1027 "gclip_select.c"
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	Block2Data* _data2_;
	GeeHashMap* _tmp0_;
	GtkWindow* _tmp1_;
	GtkWindow* window;
	GtkHBox* _tmp2_;
	GtkHBox* panel;
	GtkWindow* _tmp3_;
	GtkVBox* _tmp4_;
	GtkVBox* vbox;
	GtkScrolledWindow* _tmp5_;
	GtkScrolledWindow* _tmp6_;
	GtkScrolledWindow* _tmp7_;
	GtkTreeView* _tmp8_;
	GtkTreeView* _tmp9_;
	GtkScrolledWindow* _tmp10_;
	GtkTreeView* _tmp11_;
	GtkVBox* _tmp12_;
	GtkScrolledWindow* _tmp13_;
	GtkButton* _tmp14_;
	GtkButton* _tmp15_;
	GtkButton* _tmp16_;
	GtkButton* _tmp17_;
	GtkHBox* _tmp18_;
	GtkButton* _tmp19_;
	GtkHBox* _tmp20_;
	GtkButton* _tmp21_;
	GtkVBox* _tmp22_;
	GtkHBox* _tmp23_;
	GtkWindow* _tmp24_;
	GtkVBox* _tmp25_;
	GtkWindow* _tmp26_;
	GtkWindow* _tmp27_;
	GtkButton* _tmp28_;
	GtkButton* _tmp29_;
	GtkClipboard* _tmp30_ = NULL;
	GtkClipboard* _tmp31_;
	GtkClipboard* _tmp32_;
	gchar* _tmp33_ = NULL;
	const gchar* _tmp34_;
	GtkWindow* _tmp37_;
	GtkClipboard* _tmp38_;
	GtkTreeView* _tmp39_;
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data2_->_ref_count_ = 1;
#line 152 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_init (&args_length1, &args);
#line 154 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, GTK_TYPE_TREE_ITER, (GBoxedCopyFunc) _gtk_tree_iter_dup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 154 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (content_table);
#line 154 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	content_table = _tmp0_;
#line 156 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp1_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
#line 156 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp1_);
#line 156 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	window = _tmp1_;
#line 158 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp2_ = (GtkHBox*) gtk_hbox_new (FALSE, 4);
#line 158 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp2_);
#line 158 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	panel = _tmp2_;
#line 160 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp3_ = window;
#line 160 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_window_set_title (_tmp3_, "Clipboard Selection Manager");
#line 161 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp4_ = (GtkVBox*) gtk_vbox_new (FALSE, 10);
#line 161 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp4_);
#line 161 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	vbox = _tmp4_;
#line 163 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp5_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 163 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp5_);
#line 163 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data2_->list_view = _tmp5_;
#line 165 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp6_ = _data2_->list_view;
#line 165 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_scrolled_window_set_policy (_tmp6_, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 166 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp7_ = _data2_->list_view;
#line 166 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_scrolled_window_set_shadow_type (_tmp7_, GTK_SHADOW_ETCHED_IN);
#line 168 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp8_ = (GtkTreeView*) gtk_tree_view_new ();
#line 168 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp8_);
#line 168 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data2_->list_box = _tmp8_;
#line 169 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp9_ = _data2_->list_box;
#line 169 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	setup_list_box (_tmp9_);
#line 170 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp10_ = _data2_->list_view;
#line 170 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp11_ = _data2_->list_box;
#line 170 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_container_add ((GtkContainer*) _tmp10_, (GtkWidget*) _tmp11_);
#line 171 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp12_ = vbox;
#line 171 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp13_ = _data2_->list_view;
#line 171 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_box_pack_start ((GtkBox*) _tmp12_, (GtkWidget*) _tmp13_, TRUE, TRUE, (guint) 0);
#line 174 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp14_ = (GtkButton*) gtk_button_new_with_label ("Delete");
#line 174 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp14_);
#line 174 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (delete_button);
#line 174 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	delete_button = _tmp14_;
#line 176 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp15_ = delete_button;
#line 176 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_signal_connect_data ((GtkWidget*) _tmp15_, "button-release-event", (GCallback) ___lambda3__gtk_widget_button_release_event, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 182 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp16_ = (GtkButton*) gtk_button_new_with_label ("Delete All");
#line 182 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_object_ref_sink (_tmp16_);
#line 182 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (delete_all_button);
#line 182 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	delete_all_button = _tmp16_;
#line 183 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp17_ = delete_all_button;
#line 183 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_signal_connect_data ((GtkWidget*) _tmp17_, "button-release-event", (GCallback) ___lambda4__gtk_widget_button_release_event, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 189 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp18_ = panel;
#line 189 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp19_ = delete_button;
#line 189 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_box_pack_start ((GtkBox*) _tmp18_, (GtkWidget*) _tmp19_, FALSE, FALSE, (guint) 0);
#line 190 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp20_ = panel;
#line 190 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp21_ = delete_all_button;
#line 190 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_box_pack_start ((GtkBox*) _tmp20_, (GtkWidget*) _tmp21_, FALSE, FALSE, (guint) 0);
#line 192 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp22_ = vbox;
#line 192 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp23_ = panel;
#line 192 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_box_pack_end ((GtkBox*) _tmp22_, (GtkWidget*) _tmp23_, FALSE, FALSE, (guint) 0);
#line 193 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp24_ = window;
#line 193 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp25_ = vbox;
#line 193 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_container_add ((GtkContainer*) _tmp24_, (GtkWidget*) _tmp25_);
#line 194 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp26_ = window;
#line 194 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_window_set_default_size (_tmp26_, 200, 200);
#line 195 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp27_ = window;
#line 195 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp27_);
#line 197 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp28_ = delete_button;
#line 197 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp28_, FALSE);
#line 198 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp29_ = delete_all_button;
#line 198 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp29_, FALSE);
#line 200 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp30_ = gtk_clipboard_get (GDK_SELECTION_PRIMARY);
#line 200 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp31_ = _g_object_ref0 (_tmp30_);
#line 200 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (clip);
#line 200 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	clip = _tmp31_;
#line 201 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp32_ = clip;
#line 201 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp33_ = gtk_clipboard_wait_for_text (_tmp32_);
#line 201 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data2_->content = _tmp33_;
#line 202 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp34_ = _data2_->content;
#line 202 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	if (_tmp34_ != NULL) {
#line 1227 "gclip_select.c"
		GtkTreeView* _tmp35_;
		const gchar* _tmp36_;
#line 203 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp35_ = _data2_->list_box;
#line 203 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		_tmp36_ = _data2_->content;
#line 203 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
		add_entry_to_list_box (_tmp35_, _tmp36_);
#line 1236 "gclip_select.c"
	}
#line 205 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp37_ = window;
#line 205 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_signal_connect ((GtkWidget*) _tmp37_, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp38_ = clip;
#line 207 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_signal_connect_data (_tmp38_, "owner-change", (GCallback) ___lambda5__gtk_clipboard_owner_change, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 232 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_tmp39_ = _data2_->list_box;
#line 232 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_signal_connect_data ((GtkWidget*) _tmp39_, "size-allocate", (GCallback) ___lambda7__gtk_widget_size_allocate, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 244 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	gtk_main ();
#line 245 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	result = 0;
#line 245 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (vbox);
#line 245 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (panel);
#line 245 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_g_object_unref0 (window);
#line 245 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	block2_data_unref (_data2_);
#line 245 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	_data2_ = NULL;
#line 245 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return result;
#line 1266 "gclip_select.c"
}


int main (int argc, char ** argv) {
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	g_type_init ();
#line 150 "/media/drive2/atai/software_projects/gclip_select/gclip-select.git/gclip_select.vala"
	return _vala_main (argv, argc);
#line 1275 "gclip_select.c"
}



